import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Providers from "@web/providers"
import StickyWeb3Auth from '@web/components/StickyWeb3Auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <StickyWeb3Auth />
          {children}
        </Providers>
      </body>
    </html>
  )
}
